---
title: Week 1: Discussion Section
subtitle: Making maps with tmap and beyond
format: html
---

# 1. Get Started

```{r}
# Load packages
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
library(ggspatial)
```

```{r}
# Load data
# File contains several points on the island - volcano filter - .gpkg
ei_points <- st_read(here("Discussions","data", "easter_island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
# Raster with elevation data - .tif
ei_elev <- read_stars(here("Discussions","data", "easter_island", "ei_elev.tif"))
# Polygon with the island outline - .gpkg
ei_borders <- st_read(here("Discussions","data", "easter_island", "ei_border.gpkg"))
# Lines contains a road network for the island - .gpkg
ei_roads <- st_read(here("Discussions","data", "easter_island", "ei_roads.gpkg"))
```

# 2. Create a single-object map with tmap

```{r}
# Draw border map
tm_shape(ei_borders) +
    tm_borders() +
    tm_layout(main.title = "Easter Island Border")
```

# 3. Create a multiple-object map with tmap

```{r}
# Draw border map w/ elevation lines
# Elevation
ei_map <- tm_shape(ei_elev) +
            tm_graticules() +
            tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"), #Color gradient
                      col.legend = tm_legend("Elevation (m asl)")) +
          # Borders
          tm_shape(ei_borders) +
            tm_borders() +
          # Roads
          tm_shape(ei_roads) +
            tm_lines() +
          # Volcanos
          tm_shape(ei_points) +
            tm_symbols(shape = 24, #Triangle
                       size = "elevation", # Scale size by elevation
                       size.legend = tm_legend("Volcanoes (m asl)")) +
          tm_title("Easter Island Border") +
          tm_compass(position = c("right", "top")) +
          tm_scalebar()
ei_map
```

# 4. Create an interactive map with tmap

```{r}
# Change tmap mode to view (interactive)
tmap_mode("view")
```

```{r}
ei_map
```

```{r}
# Change tmap mode to plot (non-interactive)
tmap_mode("plot")
```

# 5. Create multiple-object map with ggplot2

```{r}
# Recreate above map w/ ggplot - non-working
elev_df <- as.data.frame(ei_elev, xy = TRUE)
colnames(elev_df) <- c("x", "y", "elevation") # Rename for clarity

ggplot(data = ei_borders) +
    geom_tile(data = elev_df, aes(x = x, y = y, fill = elevation)) +
    scale_fill_viridis_c(option = "terrain") +
    #geom_sf(ei_borders, fill = NA) +
    labs(title = "Easter Island Map",
         x = "Longitude",
         y = "Latitude")
```

```{r}
# extract lat & long from geom column 
volcanoes_point <- ei_points %>%
  mutate(lon = unlist(map(ei_points$geom,1)), # longitude = first component (x)
         lat = unlist(map(ei_points$geom,2))) # latitude = second component (y)
# Working ggplot version
ggplot() +
  # first add Easter Isand borders
  geom_sf(data = ei_borders, color = "#212529") +
  # add elevation raster
  geom_stars(data = ei_elev) +
  scale_fill_distiller(name = "Elevation (m asl)", # legend title with units
                       palette = "RdYlGn",         # red-yellow-green palette (no need to reverse)
                       na.value = "lightblue") +  # set NA color (background ocean)
  # add road vector
  geom_sf(data = ei_roads, color = "#343a40") +
  # add volcano vector
  geom_point(data = volcanoes_point, 
             aes(x = lon, y = lat, 
                 size = elevation), # point size depends on attribute value
             shape = 17,            # triangle
             color = "#22577a") +
  scale_size_continuous(name = "Volcanoes (m asl)") +       # legend title with units
  ggspatial::annotation_north_arrow(location = "br",        # bottom right
                                    which_north = "true") + # point to north pole
  ggspatial::annotation_scale(location = "bl",              # bottom left
                              width_hint = 0.5) +           # proportion of map area the scalebar should occupy
  labs(title = "Easter Island") +
  theme_minimal()
```